Raise minimum compiler for test suite to rust 1.70
With 1.61:

    error: package `indexmap v2.6.0` cannot be built because it requires
    rustc 1.63 or newer, while the currently active rustc version is 1.61.0

With 1.63:

    error: package `toml_datetime v0.6.8` cannot be built because it requires
    rustc 1.65 or newer, while the currently active rustc version is 1.63.0

With 1.65:

    error: package `trybuild v1.0.101` cannot be built because it requires
    rustc 1.70 or newer, while the currently active rustc version is 1.65.0
    Either upgrade to rustc 1.70 or newer, or use
    cargo update -p trybuild@1.0.101 --precise ver
    where `ver` is the latest version of `trybuild` supporting rustc 1.65.0