Add test of r#source that is not Error::source
Without r#source:

    error[E0599]: the method `as_dyn_error` exists for type `char`, but its trait bounds were not satisfied
      --> tests/test_source.rs:72:9
       |
    72 |         source: char,
       |         ^^^^^^ method cannot be called on `char` due to unsatisfied trait bounds
       |
       = note: the following trait bounds were not satisfied:
               `char: std::error::Error`
               which is required by `char: AsDynError<'_>`