Add regression test for issue 398
    error[E0425]: cannot find value `_0` in this scope
       --> tests/test_display.rs:308:17
        |
    308 |         #[error("{0}")]
        |                 ^^^^^ not found in this scope

    error[E0425]: cannot find value `__display_x` in this scope
       --> tests/test_display.rs:310:17
        |
    310 |         #[error("{x}")]
        |                 ^^^^^ not found in this scope